# Generated by Django 3.2.5 on 2023-08-23 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

# import django_prometheus.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
            ],
            # bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="ComponentMeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=10)),
                (
                    "unit_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            #    bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_code", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.building",
                    ),
                ),
            ],
            #   bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(999999)]
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
            ],
            #    bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_code", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.room"
                    ),
                ),
            ],
            #    bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="StorageBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_code", models.CharField(blank=True, max_length=5, null=True)),
                ("unit_row", models.CharField(blank=True, max_length=5, null=True)),
                ("unit_column", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "storage_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.storageunit",
                    ),
                ),
            ],
            # bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(blank=True, default="", max_length=100)),
                ("mpn", models.CharField(blank=True, default="", max_length=100)),
                ("upc", models.IntegerField(blank=True, default=6969)),
                (
                    "qty",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("checked_out", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.componentmeasurementunit",
                    ),
                ),
                (
                    "person_who_checkedout",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.user",
                    ),
                ),
                ("storage_bin", models.ManyToManyField(to="inventory.StorageBin")),
            ],
            #  bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
    ]
