# Generated by Django 4.2.4 on 2023-08-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentmeasurementunit',
            name='unit_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='componentmeasurementunit',
            name='unit_name',
            field=models.CharField(max_length=30),
        ),
    ]
