# Generated by Django 3.2.5 on 2023-08-24 02:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='person_who_checked_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
