# Generated by Django 4.2.4 on 2023-08-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_componentmeasurementunit_unit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component'),
        ),
    ]
