# Generated by Django 3.2.5 on 2023-08-24 15:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

# import django_prometheus.models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_auto_20230823_2219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="checked_out",
        ),
        migrations.RemoveField(
            model_name="component",
            name="person_who_checked_out",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.PositiveIntegerField(
                default=0,
                unique=True,
                validators=[django.core.validators.MaxValueValidator(999999)],
            ),
        ),
        migrations.CreateModel(
            name="Borrows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("timestamp_check_out", models.DateTimeField()),
                ("timestamp_check_in", models.DateTimeField(blank=True, null=True)),
                ("borrow_in_progress", models.BooleanField(default=True)),
                (
                    "person_who_borrowed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            #    bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.AddField(
            model_name="component",
            name="borrow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="inventory.borrows",
            ),
        ),
    ]
