# Generated by Django 4.2.4 on 2023-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_borrow_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='barcode',
            field=models.ImageField(blank=True, default='barcodes/barcode.png', upload_to='barcodes/'),
        ),
    ]
