# Generated by Django 3.2.5 on 2023-08-17 22:28

import django.core.validators
from django.db import migrations, models

#


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_auto_20210623_0537"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(999999)]
                    ),
                ),
                ("email", models.CharField(max_length=50)),
            ],
            #  bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
    ]
