# Generated by Django 4.2.4 on 2023-08-31 21:11

from django.db import migrations
import uuid


# def gen_uuid(apps, schema_editor):
#     MyModel = apps.get_model("inventory", "Component")
#     for row in MyModel.objects.all():
#         row.uuid = uuid.uuid4()
#         row.save(update_fields=["unique_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_component_unique_id"),
    ]

    operations = [
        # migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
