# Generated by Django 3.2.5 on 2023-08-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
