# Generated by Django 4.2.4 on 2023-08-31 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_auto_20230831_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
