# Generated by Django 4.2.4 on 2023-09-01 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20230831_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
