# Generated by Django 4.2.4 on 2023-09-01 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_borrow_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
