# Generated by Django 4.2.4 on 2023-09-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_component_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['timestamp_check_out']},
        ),
        migrations.AlterField(
            model_name='component',
            name='upc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
