# Generated by Django 4.2.4 on 2023-09-26 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_borrow_options_alter_component_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='qty_remaining',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
